### ISSUE TITLE
How to insert decimal number

### ISSUE THREAD

**Issue by nhoctanker** [cohenadair/angular.number-input#9]
Hi cohenadair . 
Your direct so cool. Bu how to input the decmial number when i keydown to input. 
Exmp : When i focus input and  keydown with 1.523 It's not working

**Comment by cohenadair** [comment]
It would appear to be a bug, unfortunately.  With the right setup you can add a decimal but you can't add any numbers after the decimal.

I'll add it to my list of things to do.  Thanks for letting me know!

**Comment by cohenadair** [comment]
I actually can't reproduce this.  When I tested it initially it wasn't working because 1.523 fell outside the provided range.

So make sure that you've set your max and min correctly and see if it still happens.

**Comment by cohenadair** [comment]
I managed to reproduce this.  It happens because part of the input validation process checks the length of the input and compares it to the max and min string lengths.  This process didn't take into consideration decimal places.  Basically the comparison max length was (1 + number of decimal places) too short.

And this only occurred on directives that had the max and/or min properties set.

This has been fixed for the next version.
